web:
    build: .
    ports:
        - "80:80"
    volumes:
        - ./src:/var/www/html
    links:
        - db
db:
    image: mysql:5.6
    volumes:
        - ./db:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: r00+
        MYSQL_DATABASE: superproxy
        MYSQL_USER: superproxy
        MYSQL_PASSWORD: $uperpr0xy
